framework:
    secret: '%env(APP_SECRET)%'

    php_errors:
        log: true

    trusted_proxies: '127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,REMOTE_ADDR'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-port'] # 'x-forwarded-host' not trusted by default
