framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: '%env(REDIS_DSN)%'
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    trusted_proxies: '127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port']
