framework:
    messenger:
        transports:
#             async: '%env(MESSENGER_TRANSPORT_DSN)%'
             sync: 'sync://'

        routing:
             'App\Message\Funding\SendOrderCaptureSummaryMail': sync
             'App\Message\Funding\SendOrderRefundMail': sync
             'App\Domain\Event\DeletedUser': sync
