framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        default_bus: event.bus
        buses:
            event.bus: ~
#                default_middleware: allow_no_handlers
        failure_transport: failed
        transports:
            failed: '%env(MESSENGER_TRANSPORT_FAILED_DSN)%'
            organizations_sub:
                dsn: '%env(MESSENGER_TRANSPORT_ORGANIZATIONS_SUB_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
            my_fleet_internal: 'sync://'
            sync: 'sync://'

        routing:
            'App\Message\Funding\SendOrderCaptureSummaryMail': sync
            'App\Message\Funding\SendOrderRefundMail': sync
            'App\Domain\Event\DeletedUserEvent': [ my_fleet_internal, organizations_sub ]
            'App\Domain\Event\UpdatedFleetShipEvent': [ organizations_sub ]
            'App\Domain\Event\DeletedFleetShipEvent': [ organizations_sub ]
