security:
    #    enable_authenticator_manager: true
    providers:
        user_entity_jwt:
            id: 'App\Security\UserEntityJwtProvider'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|favicon\.ico)/
            security: false
        main:
            provider: user_entity_jwt
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - jwt_auth.security.guard.jwt_guard_authenticator
            logout:
                path: logout
            access_denied_handler: App\Security\ApiAccessDeniedHandler

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/bo/, roles: ROLE_ADMIN }
        - { path: ^/,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
