version: '3.4'
services:
    php:
        build:
            context: .
            target: build_php
            dockerfile: ./docker/Dockerfile
            args:
                DUMP_ENV: 1
        hostname: php
    apache:
        build:
            context: .
            target: build_apache
            dockerfile: ./docker/Dockerfile
        hostname: apache
        environment:
            PHP_HANDLER_HOST: php:9000
        depends_on:
            - php
    redis:
        image: bitnami/redis:5.0.5-debian-9-r56
        hostname: redis
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
