version: '3.5'
services:
    php:
        image: 186694923554.dkr.ecr.eu-west-1.amazonaws.com/fleet-manager-api-php:test-latest
        hostname: php
        depends_on:
            - redis
    supervisor:
        image: 186694923554.dkr.ecr.eu-west-1.amazonaws.com/fleet-manager-api-supervisor:test-latest
        hostname: supervisor
        depends_on:
            - redis
    apache:
        image: 186694923554.dkr.ecr.eu-west-1.amazonaws.com/fleet-manager-api-apache:test-latest
        hostname: apache
        environment:
            PHP_HANDLER_HOST: php:9000
        depends_on:
            - php
    redis:
        image: bitnami/redis:5.0.9-debian-10-r6
        hostname: redis
