version: '3.5'
services:
    php:
        image: 186694923554.dkr.ecr.eu-west-1.amazonaws.com/fleet-manager-api-php:test-latest
        hostname: php
        depends_on:
            postgres:
                condition: service_healthy
    apache:
        image: 186694923554.dkr.ecr.eu-west-1.amazonaws.com/fleet-manager-api-apache:test-latest
        hostname: apache
        depends_on: [php]
        environment:
            PHP_HANDLER_HOST: php:9000
        ports:
            - 127.0.0.1:80:80
    postgres:
        image: postgres:13-alpine
        hostname: postgres
        command: ['postgres', '-c', 'config_file=/etc/postgresql/postgresql.conf']
        tmpfs:
            - /var/lib/postgresql/data
        volumes:
            - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
            - 127.0.0.1:5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 1s
            timeout: 2s
            retries: 20
