parameters:
    env(MONOLOG_MAILER_TO_0): 'root@localhost'

monolog:
    handlers:
        main:
            type: stream
            path: "php://stderr"
            level: debug
            channels: [ "!event" ]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        ##########################
        fingers:
            type: fingers_crossed
            action_level: error
            handler: dedup_mail
            buffer_size: 50
        dedup_mail:
            type: deduplication
            time: 5
            store: '/tmp/monolog_handler_deduplicated'
            handler: mailer
        mailer:
            type: symfony_mailer
            from_email: 'noreply@fleet-manager.space'
            to_email: '%env(MONOLOG_MAILER_TO_0)%'
            subject: '[FM API %kernel.environment%] Error : %%message%%'
            formatter: monolog.formatter.html
            content_type: text/html
