monolog:
    channels: [deprecation]
    handlers:
        deprecation:
            type: rotating_file
            max_files: 5
            channels: [deprecation]
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
