parameters:
    env(MONOLOG_MAILER_TO): ''
    env(MAILER_NOREPLY_ADDRESS): 'noreply@fleet-manager.space'

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
            excluded_http_codes: [404, 405]
            buffer_size:  50 # How many messages should be saved? Prevent memory leaks
        grouped:
            type:    group
            members: [streamed_error, dedup_mail]
        streamed_error:
            type: rotating_file
            max_files: 10
            path: "%kernel.logs_dir%/%kernel.environment%-error.log"
        #######
        filter:
            type: filter
            handler: streamed_main
            min_level: 'info'
            max_level: 'warning'
        streamed_main:
            type: rotating_file
            max_files: 10
            path: "%kernel.logs_dir%/%kernel.environment%.log"
        #######
#        elasticsearch:
#            elasticsearch:
#                host: elasticsearch
#                port: 9200
#            index: monolog
#            document_type: logs
#            level: info
        ########
        fingers_mail:
            type: fingers_crossed
            action_level: warning
            handler: dedup_mail
            excluded_http_codes: [403, 404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        dedup_mail:
            type: deduplication
            time: 60 # no duplicated messages within 60 seconds
            store: '%kernel.logs_dir%/monolog_handler_deduplicated'
            handler: mailer
        mailer:
            type: swift_mailer
            from_email: '%env(MAILER_NOREPLY_ADDRESS)%'
            to_email: '%env(MONOLOG_MAILER_TO)%'
            subject: '[FM Monolog] Error : %%message%%'
            formatter: monolog.formatter.html
            content_type: text/html
        ########
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
