parameters:
    env(MONOLOG_MAILER_TO): 'root@localhost'

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: dedup_mail
            excluded_http_codes: [404, 405]
            buffer_size:  50 # How many messages should be saved? Prevent memory leaks
        dedup_mail:
            type: deduplication
            time: 60 # no duplicated messages within 60 seconds
            store: '%kernel.logs_dir%/monolog_handler_deduplicated'
            handler: mailer
        mailer:
            type: symfony_mailer
            from_email: 'noreply@fleet-manager.space'
            to_email: ['%env(MONOLOG_MAILER_TO)%']
            subject: '[FM Monolog prod] Error : %%message%%'
            formatter: monolog.formatter.html
            content_type: text/html
        ################
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
