parameters:
    env(MONOLOG_MAILER_TO_0): 'root@localhost'
    env(MONOLOG_MAILER_TO_1): 'root@localhost'

monolog:
    channels: [ deprecation ]
    handlers:
        main:
            type: stream
            path: "php://stderr"
            level: info
            formatter: monolog.formatter.json
            channels: ["!event"]
        ################
        fingers:
            type: fingers_crossed
            action_level: error
            handler: dedup_mail
            excluded_http_codes: [401, 403, 404, 405]
            buffer_size: 50
        dedup_mail:
            type: deduplication
            time: 60 # no duplicated messages within 60 seconds
            store: '/tmp/monolog_handler_deduplicated'
            handler: mailer
        mailer:
            type: symfony_mailer
            level: info
            from_email: 'noreply@fleet-manager.space'
            to_email:
                - '%env(MONOLOG_MAILER_TO_0)%'
                - '%env(MONOLOG_MAILER_TO_1)%'
            subject: '[FM API %kernel.environment%] Error : %%message%%'
            formatter: monolog.formatter.html
            content_type: text/html
        ################
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        ################
        deprecation:
            type: stream
            path: "php://stderr"
            formatter: monolog.formatter.json
            channels: [deprecation]
