parameters:
    env(SENTRY_DSN): ''

sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'

services:
    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - 'Symfony\Component\Security\Core\Exception\AccessDeniedException'
                    - 'Symfony\Component\Security\Core\Exception\AuthenticationException'
                    - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
