imports:
    - { resource: services_test.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Application\Repository\UserRepositoryInterface: '@App\Infrastructure\Repository\User\InMemoryUserRepository'
    App\Application\Repository\PatchNoteRepositoryInterface: '@App\Infrastructure\Repository\PatchNote\InMemoryPatchNoteRepository'
    App\Application\Repository\FleetRepositoryInterface: '@App\Infrastructure\Repository\Fleet\InMemoryFleetRepository'
    App\Application\Repository\OrganizationRepositoryInterface: '@App\Infrastructure\Repository\Organization\InMemoryOrganizationRepository'

    App\Application\Common\Clock: '@App\Infrastructure\Common\FakeClock'

    Symfony\Component\Validator\Validator\ValidatorInterface: '@validator'
