parameters:
    env(REDIS_DSN): ''
    currency: 'USD'
    env(PAYPAL_CHECKOUT_CLIENT_ID): ''
    env(PAYPAL_CHECKOUT_CLIENT_SECRET): ''
    env(PAYPAL_CHECKOUT_WEBHOOK_ID): ''
    env(PAYPAL_CHECKOUT_MODE): !php/const App\Service\Funding\PayPalHttpClientFactory::MODE_SANDBOX

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $registrationFromAddress: 'noreply@fleet-manager.space'
            $noreplyAddress: 'noreply@fleet-manager.space'

    App\:
        resource: '../src'
        exclude:
            - '../src/Application/**/*/Output'
            - '../src/Application/Exception'
            - '../src/Infrastructure/**/*/Input'
            - '../src/Domain'
            - '../src/Entity'
            - '../src/Message'
            - '../src/Event'
            - '../src/*/Dto'
            - '../src/*/*/Dto'
            - '../src/*/Exception'
            - '../src/Validator/Constraints/UniqueField.php'
    App\Controller\:
        resource: '../src/Controller/**/*Controller.php'
        tags: ['controller.service_arguments']
    App\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller/**/*Controller.php'
        tags: ['controller.service_arguments']

    App\MessageHandler\Funding\SendOrderCaptureSummaryMailHandler:
        arguments:
            $orderCaptureSummaryAddresses: '%env(csv:FUNDING_ORDER_CAPTURE_ADDRESSES)%'

    App\Listener\Funding\UpdateSupporterAdvantagesListener:
        tags:
            - { name: 'kernel.event_listener' }

    App\Service\Funding\PaypalCheckout: ~
    App\Service\Funding\PaypalCheckoutInterface: '@App\Service\Funding\PaypalCheckout'

    App\Service\Funding\VerifyWebhookSignatureFactory:
        arguments:
            $webhookId: '%env(PAYPAL_CHECKOUT_WEBHOOK_ID)%'

    App\Service\Funding\PayPalHttpClientFactory:
        arguments:
            $clientId: '%env(PAYPAL_CHECKOUT_CLIENT_ID)%'
            $clientSecret: '%env(PAYPAL_CHECKOUT_CLIENT_SECRET)%'
            $mode: '%env(PAYPAL_CHECKOUT_MODE)%'

    App\Controller\Funding\ConfigurationController:
        arguments:
            $currency: '%currency%'
            $paypalClientId: '%env(PAYPAL_CHECKOUT_CLIENT_ID)%'
        tags: ['controller.service_arguments']

    PayPalCheckoutSdk\Core\PayPalHttpClient:
        factory: ['@App\Service\Funding\PayPalHttpClientFactory', 'createPayPalHttpClient']
    PayPal\Rest\ApiContext:
        factory: ['@App\Service\Funding\PayPalHttpClientFactory', 'createApiContext']

    App\Application\Repository\UserRepositoryInterface: '@App\Infrastructure\Repository\User\DoctrineUserRepository'
    App\Application\Repository\PatchNoteRepositoryInterface: '@App\Infrastructure\Repository\PatchNote\DoctrinePatchNoteRepository'
