imports:
    - { resource: services_test.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Application\Repository\UserRepositoryInterface: '@App\Infrastructure\Repository\User\InMemoryUserRepository'
    App\Application\Repository\PatchNoteRepositoryInterface: '@App\Infrastructure\Repository\PatchNote\InMemoryPatchNoteRepository'
