services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Tests\Service\PayPal\MockPayPalHttpClient: ~
    App\Tests\Service\PayPal\MockVerifyWebhookSignatureFactory: ~
    App\Service\Funding\PaypalCheckout:
        arguments:
            $client: '@App\Tests\Service\PayPal\MockPayPalHttpClient'
            $verifyWebhookSignatureFactory: '@App\Tests\Service\PayPal\MockVerifyWebhookSignatureFactory'
