parameters:
    env(REDIS_DSN): ''
    currency: 'USD'
    env(PAYPAL_CHECKOUT_CLIENT_ID): ''
    env(PAYPAL_CHECKOUT_CLIENT_SECRET): ''
    env(PAYPAL_CHECKOUT_WEBHOOK_ID): ''
    env(PAYPAL_CHECKOUT_MODE): !php/const App\Service\Funding\PayPalHttpClientFactory::MODE_SANDBOX
    env(MAILER_NOREPLY_ADDRESS): 'noreply@fleet-manager.space'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $profileLinkAccountLogger: '@monolog.logger.profile_link_account'
            $registrationFromAddress: '%env(MAILER_NOREPLY_ADDRESS)%'
            $noreplyAddress: '%env(MAILER_NOREPLY_ADDRESS)%'

    App\:
        resource: '../src'
        exclude:
            - '../src/Domain'
            - '../src/Message'
            - '../src/*/Dto'
            - '../src/*/*/Dto'
            - '../src/*/Exception'
            - '../src/Validator/Constraints/UniqueField.php'
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    hwi_oauth.authentication.entry_point.oauth:
        class: App\Security\OAuthEntryPoint
        abstract: true
        arguments: ['@http_kernel', '@security.http_utils']

    App\Security\Listener\AlreadyLinkedDiscordListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onException' }

    App\MessageHandler\Funding\SendOrderCaptureSummaryMailHandler:
        arguments:
            $orderCaptureSummaryAddresses: '%env(csv:FUNDING_ORDER_CAPTURE_ADDRESSES)%'

    App\Listener\Funding\UpdateSupporterAdvantagesListener:
        tags:
            - { name: 'kernel.event_listener' }

    App\Service\Funding\PaypalCheckout: ~
    App\Service\Funding\PaypalCheckoutInterface: '@App\Service\Funding\PaypalCheckout'

    App\Service\Funding\VerifyWebhookSignatureFactory:
        arguments:
            $webhookId: '%env(PAYPAL_CHECKOUT_WEBHOOK_ID)%'

    App\Service\Funding\PayPalHttpClientFactory:
        arguments:
            $clientId: '%env(PAYPAL_CHECKOUT_CLIENT_ID)%'
            $clientSecret: '%env(PAYPAL_CHECKOUT_CLIENT_SECRET)%'
            $mode: '%env(PAYPAL_CHECKOUT_MODE)%'

    App\Controller\Funding\ConfigurationController:
        arguments:
            $currency: '%currency%'
            $paypalClientId: '%env(PAYPAL_CHECKOUT_CLIENT_ID)%'
        tags: ['controller.service_arguments']

    PayPalCheckoutSdk\Core\PayPalHttpClient:
        factory: ['@App\Service\Funding\PayPalHttpClientFactory', 'createPayPalHttpClient']
    PayPal\Rest\ApiContext:
        factory: ['@App\Service\Funding\PayPalHttpClientFactory', 'createApiContext']
