services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Application\:
        resource: '../src/Application'
        exclude:
            - '../src/Application/**/*/Input'
            - '../src/Application/**/*/Output'
            - '../src/Application/Exception'
            - '../src/Infrastructure/**/*/Input'

    App\Tests\Service\PayPal\MockPayPalHttpClient: ~
    App\Tests\Service\PayPal\MockVerifyWebhookSignatureFactory: ~
    App\Service\Funding\PaypalCheckout:
        arguments:
            $client: '@App\Tests\Service\PayPal\MockPayPalHttpClient'
            $verifyWebhookSignatureFactory: '@App\Tests\Service\PayPal\MockVerifyWebhookSignatureFactory'

    App\Infrastructure\Security\FakeAuth0Service:
        parent: 'jwt_auth.auth0_service'
    Auth0\JWTAuthBundle\Security\Auth0Service: '@App\Infrastructure\Security\FakeAuth0Service'

    App\Application\Repository\Auth0RepositoryInterface: '@App\Infrastructure\Repository\User\FakeAuth0Repository'
